<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20220518161022.1"><vh>@settings</vh>
<v t="leo.20220518161022.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="leo.20220518161022.3"><vh>@string initial_split_orientation = horizontal</vh></v>
<v t="leo.20220518161101.1"><vh>@@data import-xml-tags</vh></v>
</v>
<v t="leo.20220518161142.1"><vh>recursive importer</vh></v>
<v t="leo.20220622162507.1"><vh>imported files</vh>
<v t="leo.20220622162507.2"><vh>@path ./</vh>
<v t="leo.20220622162507.3"><vh>@clean gfSearch.html</vh>
<v t="leo.20220622162507.4"><vh>&lt;html&gt; (gfSearch.html)</vh>
<v t="leo.20220622162507.5"><vh>&lt;head&gt; (gfSearch.html)</vh>
<v t="leo.20220622162507.6"><vh>&lt;meta http-equiv="Content-Language" content="en-us"&gt; (gfSearch.html)</vh>
<v t="leo.20220622162507.7"><vh>&lt;link rel="stylesheet" type="text/css" href="style.css"&gt; (gfSearch.html)</vh>
<v t="leo.20220622162507.8"><vh>&lt;style type="text/css"&gt; (gfSearch.html)</vh></v>
</v>
<v t="leo.20220622162507.9"><vh>&lt;body&gt; (gfSearch.html)</vh>
<v t="leo.20220622162507.10"><vh>&lt;script&gt; (gfSearch.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20220622162507.11"><vh>@clean gSearch.html</vh>
<v t="leo.20220622162507.12"><vh>&lt;html&gt; (gSearch.html)</vh>
<v t="leo.20220622162507.13"><vh>&lt;head&gt; (gSearch.html)</vh>
<v t="leo.20220622162507.14"><vh>&lt;meta http-equiv="Content-Language" content="en-us"&gt; (gSearch.html)</vh>
<v t="leo.20220622162507.15"><vh>&lt;link rel="stylesheet" type="text/css" href="style.css"&gt; (gSearch.html)</vh>
<v t="leo.20220622162507.16"><vh>&lt;style type="text/css"&gt; (gSearch.html)</vh></v>
</v>
<v t="leo.20220622162507.17"><vh>&lt;body&gt; (gSearch.html)</vh>
<v t="leo.20220622162507.18"><vh>&lt;script&gt; (gSearch.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20220622162507.19"><vh>@clean index.html</vh>
<v t="leo.20220622162507.20"><vh>&lt;html&gt; (index.html)</vh>
<v t="leo.20220622162507.21"><vh>&lt;head&gt; (index.html)</vh>
<v t="leo.20220622162507.22"><vh>&lt;meta http-equiv="Content-Language" content="en-us"&gt; (index.html)</vh></v>
<v t="leo.20220622162507.23"><vh>&lt;frameset cols="400,*" frameborder="1" framespacing="4" bordercolor="#0B6DCE" border="4"&gt; (index.html)</vh>
<v t="leo.20220622162507.24"><vh>&lt;frameset rows="54,*" frameborder="0" framespacing="0" bordercolor="#0B6DCE"&gt; (index.html)</vh>
<v t="leo.20220622162507.25"><vh>&lt;frame name="wb_bar" scrolling="no" src="wb_bar.html" frameborder="0" target="wb_cont"&gt; (index.html)</vh>
<v t="leo.20220622162507.26"><vh>&lt;frame name="wb_tree" src="wb_tree.html" frameborder="1" target="wb_cont"&gt; (index.html)</vh></v>
<v t="leo.20220622162507.27"><vh>&lt;frame name="wb_cont" src="en/welcome.htm" frameborder="0"&gt; (index.html)</vh></v>
<v t="leo.20220622162507.28"><vh>&lt;noframes&gt; (index.html)</vh>
<v t="leo.20220622162507.29"><vh>&lt;body&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20220622162507.30"><vh>@clean ssSearch.html</vh>
<v t="leo.20220622162507.31"><vh>&lt;html&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.32"><vh>&lt;head&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.33"><vh>&lt;link rel="stylesheet" type="text/css" href="style.css"&gt; (ssSearch.html)</vh></v>
<v t="leo.20220622162507.34"><vh>&lt;body&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.35"><vh>&lt;blockquote&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.36"><vh>&lt;center&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.37"><vh>&lt;applet code="ssSearch.class" width="640" height="480"&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.38"><vh>&lt;param name="BGCOLOR" value="0B6DCE"&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.39"><vh>&lt;param name="LISTAREACOLOR" value="ffffff"&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.40"><vh>&lt;param name="TARGETFRAME" value="_self"&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.41"><vh>&lt;param name="DATAFILE" value="wb_search.txt"&gt; (ssSearch.html)</vh>
<v t="leo.20220622162507.42"><vh>&lt;param name="APPLETHOME" value="http://www.geocities.com/SiliconValley/Lakes/5365/index.html"&gt; (ssSearch.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20220622162507.43"><vh>@clean wb_bar.html</vh>
<v t="leo.20220622162507.44"><vh>&lt;html&gt; (wb_bar.html)</vh>
<v t="leo.20220622162507.45"><vh>&lt;head&gt; (wb_bar.html)</vh>
<v t="leo.20220622162507.46"><vh>&lt;meta http-equiv="Content-Language" content="en-us" &gt; (wb_bar.html)</vh>
<v t="leo.20220622162507.47"><vh>&lt;base target="wb_cont"&gt; (wb_bar.html)</vh>
<v t="leo.20220622162507.48"><vh>&lt;style type="text/css"&gt; (wb_bar.html)</vh></v>
</v>
<v t="leo.20220622162507.49"><vh>&lt;body style="margin: 2px; background-color: #F1F1F1"&gt; (wb_bar.html)</vh>
<v t="leo.20220622162507.50"><vh>&lt;div class="navigation"&gt; (wb_bar.html)</vh>
<v t="leo.20220622162507.51"><vh>&lt;p&gt; (wb_bar.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20220622162507.52"><vh>@clean wb_tree.html</vh>
<v t="leo.20220622162507.53"><vh>&lt;html&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.54"><vh>&lt;head&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.55"><vh>&lt;meta http-equiv="Content-Language" content="en-us" &gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.56"><vh>&lt;base target="wb_cont"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.57"><vh>&lt;style type="text/css"&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.58"><vh>&lt;script type="text/javascript"&gt; (wb_tree.html)</vh></v>
</v>
<v t="leo.20220622162507.59"><vh>&lt;body style="margin: 2px; background-color: #F1F1F1" onload="showStartPage()"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.60"><vh>&lt;div class="tree" onmouseout="clearLastLink()"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.61"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.62"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.63"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.64"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.65"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.66"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.67"><vh>&lt;div id="folder.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.68"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.69"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.70"><vh>&lt;div id="folder.1.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.71"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.72"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.73"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.74"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.75"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.76"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.77"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.78"><vh>&lt;div id="folder.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.79"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.80"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.81"><vh>&lt;div id="folder.2.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.82"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.83"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.84"><vh>&lt;div id="folder.3"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.85"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.86"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.87"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.88"><vh>&lt;div id="folder.4"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.89"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.90"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.91"><vh>&lt;div id="folder.4.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.92"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.93"><vh>&lt;div id="folder.4.1.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.94"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.95"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.96"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.97"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.98"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.99"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.100"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.101"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.102"><vh>&lt;div id="folder.4.1.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.103"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.104"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.105"><vh>&lt;div id="folder.4.1.3"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.106"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.107"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.108"><vh>&lt;div id="folder.4.1.4"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.109"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.110"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.111"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.112"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.113"><vh>&lt;div id="folder.4.1.4.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.114"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.115"><vh>&lt;div id="folder.4.1.4.1.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.116"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.117"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.118"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.119"><vh>&lt;div id="folder.4.1.4.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.120"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.121"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.122"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.123"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.124"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.125"><vh>&lt;div id="folder.4.1.5"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.126"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.127"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.128"><vh>&lt;div id="folder.4.1.5.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.129"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.130"><vh>&lt;div id="folder.4.1.5.1.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.131"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.132"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.133"><vh>&lt;div id="folder.4.1.6"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.134"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.135"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.136"><vh>&lt;div id="folder.4.1.7"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.137"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.138"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.139"><vh>&lt;div id="folder.4.1.8"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.140"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.141"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.142"><vh>&lt;div id="folder.4.1.8.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.143"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.144"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.145"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.146"><vh>&lt;div id="folder.4.1.9"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.147"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.148"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.149"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.150"><vh>&lt;div id="folder.4.1.10"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.151"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.152"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.153"><vh>&lt;div id="folder.4.1.11"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.154"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.155"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.156"><vh>&lt;div id="folder.4.1.12"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.157"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.158"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.159"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.160"><vh>&lt;div id="folder.5"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.161"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.162"><vh>&lt;div id="folder.5.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.163"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.164"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.165"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.166"><vh>&lt;div id="folder.5.1.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.167"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.168"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.169"><vh>&lt;div id="folder.5.1.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.170"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.171"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.172"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.173"><vh>&lt;div id="folder.5.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.174"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.175"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.176"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.177"><vh>&lt;div id="folder.5.2.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.178"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.179"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.180"><vh>&lt;div id="folder.5.2.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.181"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.182"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.183"><vh>&lt;div id="folder.5.3"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.184"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.185"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.186"><vh>&lt;div id="folder.5.3.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.187"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.188"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.189"><vh>&lt;div id="folder.5.4"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.190"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.191"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.192"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.193"><vh>&lt;div id="folder.5.5"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.194"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.195"><vh>&lt;div id="folder.5.5.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.196"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.197"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.198"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.199"><vh>&lt;div id="folder.5.5.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.200"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.201"><vh>&lt;div id="folder.5.5.2.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.202"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.203"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.204"><vh>&lt;div id="folder.5.5.2.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.205"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.206"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.207"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.208"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.209"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.210"><vh>&lt;div id="folder.5.6"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.211"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.212"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.213"><vh>&lt;div id="folder.5.7"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.214"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.215"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.216"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.217"><vh>&lt;div id="folder.5.8"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.218"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.219"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.220"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.221"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.222"><vh>&lt;div id="folder.5.9"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.223"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.224"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.225"><vh>&lt;div id="folder.5.9.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.226"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.227"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.228"><vh>&lt;div id="folder.5.9.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.229"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.230"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.231"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.232"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.233"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.234"><vh>&lt;div id="folder.5.10"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.235"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.236"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.237"><vh>&lt;div id="folder.5.11"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.238"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.239"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.240"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.241"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.242"><vh>&lt;div id="folder.6"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.243"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.244"><vh>&lt;div id="folder.6.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.245"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.246"><vh>&lt;div id="folder.6.1.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.247"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.248"><vh>&lt;div id="folder.6.1.1.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.249"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.250"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.251"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.252"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.253"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.254"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.255"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.256"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.257"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.258"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.259"><vh>&lt;div id="folder.6.1.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.260"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.261"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.262"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.263"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.264"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.265"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.266"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.267"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.268"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.269"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.270"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.271"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.272"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.273"><vh>&lt;div id="folder.6.2"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.274"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.275"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.276"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.277"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.278"><vh>&lt;div id="folder.7"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.279"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.280"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.281"><vh>&lt;div id="folder.8"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.282"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.283"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.284"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.285"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.286"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.287"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.288"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.289"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.290"><vh>&lt;div id="folder.8.1"&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.291"><vh>&lt;p&gt; (wb_tree.html)</vh>
<v t="leo.20220622162507.292"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
<v t="leo.20220622162507.293"><vh>&lt;p&gt; (wb_tree.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20220622162507.294"><vh>@path en</vh>
<v t="leo.20220622162507.295"><vh>@path images</vh></v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="leo.20220518161022.1"></t>
<t tx="leo.20220518161022.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 30px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 30px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 30px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 30px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 30px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 30px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="leo.20220518161022.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="leo.20220518161101.1">UsesMasterModel
Units
References
PaletteEntry
TemplateFileType
ObjectData
PreviewImage
Filename
Palette
Presentation</t>
<t tx="leo.20220518161142.1">'''Recursively import all python files in a directory and clean the result.'''
# ctrl + b to execute

c.recursiveImport(
    dir_ = r'./',
    kind = '@clean', # The new best practice.
    safe_at_file = False,
    theTypes = ['.html'] 
)</t>
<t tx="leo.20220622162507.1"></t>
<t tx="leo.20220622162507.10">&lt;script&gt;
  (function() {
    var cx = '000323407853036022547:_o4g_stjndu';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
&lt;/script&gt;
&lt;gcse:search&gt;&lt;/gcse:search&gt;

</t>
<t tx="leo.20220622162507.100">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link32folder.4.1" href="en/layerSelectionDialog.htm"&gt;Layer selection dialog&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.101">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.2" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.2')"&gt;&lt;a name="link33folder.4.1.2" class="el" href="en/cameras.htm"&gt;Cameras&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.102">          &lt;div id="folder.4.1.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.103">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link34folder.4.1.2" href="en/cameraPropertiesDialog.htm"&gt;Camera properties&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.104">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.3" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.3')"&gt;&lt;a name="link35folder.4.1.3" class="el" href="en/lights.htm"&gt;Lights&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.105">          &lt;div id="folder.4.1.3"&gt;
    @others
</t>
<t tx="leo.20220622162507.106">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link36folder.4.1.3" href="en/lightPropertiesDialog.htm"&gt;Light properties&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.107">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.4" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.4')"&gt;&lt;a name="link37folder.4.1.4" class="el" href="en/shapes.htm"&gt;Shapes&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.108">          &lt;div id="folder.4.1.4"&gt;
    @others
</t>
<t tx="leo.20220622162507.109">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link38folder.4.1.4" href="en/shapeReferenceFrames.htm"&gt;Shape coordinate frame&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.11">@path ./
@others
@language xml
@tabwidth -4
</t>
<t tx="leo.20220622162507.110">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link39folder.4.1.4" href="en/primitiveShapes.htm"&gt;Primitive shapes&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.111">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link40folder.4.1.4" href="en/convexDecomposition.htm"&gt;Convex decomposition&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.112">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.4.1.4.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.4.1')"&gt;&lt;a name="link41folder.4.1.4.1" class="el" href="en/shapeProperties.htm"&gt;Shape properties&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.113">            &lt;div id="folder.4.1.4.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.114">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.4.1.4.1.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.4.1.1')"&gt;&lt;a name="link42folder.4.1.4.1.1" class="el" href="en/shapeDynamicsProperties.htm"&gt;Shape dynamics properties&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.115">              &lt;div id="folder.4.1.4.1.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.116">                &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link43folder.4.1.4.1.1" href="en/shapeDynamicEngineProperties.htm"&gt;Material properties&lt;/a&gt;&lt;/p&gt;
              &lt;/div&gt;
</t>
<t tx="leo.20220622162507.117">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link44folder.4.1.4.1" href="en/geometryDialog.htm"&gt;Shape geometry dialog&lt;/a&gt;&lt;/p&gt;
            &lt;/div&gt;
</t>
<t tx="leo.20220622162507.118">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.4.1.4.2" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.4.1.4.2')"&gt;&lt;a name="link45folder.4.1.4.2" class="el" href="en/shapeEditModes.htm"&gt;Shape edit modes&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.119">            &lt;div id="folder.4.1.4.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.12">&lt;html&gt;
    @others
</t>
<t tx="leo.20220622162507.120">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link46folder.4.1.4.2" href="en/triangleEditMode.htm"&gt;Triangle edit mode&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.121">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link47folder.4.1.4.2" href="en/vertexEditMode.htm"&gt;Vertex edit mode&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.122">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link48folder.4.1.4.2" href="en/edgeEditMode.htm"&gt;Edge edit mode&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.123">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link49folder.4.1.4.2" href="en/groupedShapeEditMode.htm"&gt;Edit mode for compound shapes&lt;/a&gt;&lt;/p&gt;
            &lt;/div&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.124">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.5" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.5')"&gt;&lt;a name="link50folder.4.1.5" class="el" href="en/joints.htm"&gt;Joints&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.125">          &lt;div id="folder.4.1.5"&gt;
    @others
</t>
<t tx="leo.20220622162507.126">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link51folder.4.1.5" href="en/jointModes.htm"&gt;Joint modes&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.127">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.4.1.5.1" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.4.1.5.1')"&gt;&lt;a name="link52folder.4.1.5.1" class="el" href="en/jointProperties.htm"&gt;Joint properties&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.128">            &lt;div id="folder.4.1.5.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.129">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.5.1.1" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.4.1.5.1.1')"&gt;&lt;a name="link53folder.4.1.5.1.1" class="el" href="en/jointDynamicsProperties.htm"&gt;Joint dynamics properties&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.13">&lt;head&gt;
    @others
</t>
<t tx="leo.20220622162507.130">              &lt;div id="folder.4.1.5.1.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.131">                &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link54folder.4.1.5.1.1" href="en/jointDynamicEngineProperties.htm"&gt;Dynamics engines properties related to joints&lt;/a&gt;&lt;/p&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.132">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.6" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.6')"&gt;&lt;a name="link55folder.4.1.6" class="el" href="en/dummies.htm"&gt;Dummies&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.133">          &lt;div id="folder.4.1.6"&gt;
    @others
</t>
<t tx="leo.20220622162507.134">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link56folder.4.1.6" href="en/dummyPropertiesDialog.htm"&gt;Dummy properties&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.135">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.7" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.7')"&gt;&lt;a name="link57folder.4.1.7" class="el" href="en/graphs.htm"&gt;Graphs&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.136">          &lt;div id="folder.4.1.7"&gt;
    @others
</t>
<t tx="leo.20220622162507.137">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link58folder.4.1.7" href="en/graphPropertiesDialog.htm"&gt;Graph properties&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.138">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.8" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.8')"&gt;&lt;a name="link59folder.4.1.8" class="el" href="en/proximitySensors.htm"&gt;Proximity sensors&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.139">          &lt;div id="folder.4.1.8"&gt;
    @others
</t>
<t tx="leo.20220622162507.14">&lt;meta http-equiv="Content-Language" content="en-us"&gt;
&lt;title&gt;gSearch&lt;/title&gt;
    @others
&lt;/html&gt;
</t>
<t tx="leo.20220622162507.140">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link60folder.4.1.8" href="en/proximitySensorDescription.htm"&gt;Proximity sensor types and mode of operation&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.141">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.4.1.8.1" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.4.1.8.1')"&gt;&lt;a name="link61folder.4.1.8.1" class="el" href="en/proximitySensorPropertiesDialog.htm"&gt;Proximity sensor properties&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.142">            &lt;div id="folder.4.1.8.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.143">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link62folder.4.1.8.1" href="en/proximitySensorVolumeDialog.htm"&gt;Proximity sensor volume dialog&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.144">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link63folder.4.1.8.1" href="en/proximitySensorDetectionParameterDialog.htm"&gt;Proximity sensor detection parameter dialog&lt;/a&gt;&lt;/p&gt;
            &lt;/div&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.145">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.9" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.9')"&gt;&lt;a name="link64folder.4.1.9" class="el" href="en/visionSensors.htm"&gt;Vision sensors&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.146">          &lt;div id="folder.4.1.9"&gt;
    @others
</t>
<t tx="leo.20220622162507.147">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link65folder.4.1.9" href="en/visionSensorDescription.htm"&gt;Vision sensor types and mode of operation&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.148">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link66folder.4.1.9" href="en/visionSensorPropertiesDialog.htm"&gt;Vision sensor properties&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.149">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.10" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.10')"&gt;&lt;a name="link67folder.4.1.10" class="el" href="en/forceSensors.htm"&gt;Force sensors&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.15">&lt;link rel="stylesheet" type="text/css" href="style.css"&gt;

    @others
&lt;/head&gt;
</t>
<t tx="leo.20220622162507.150">          &lt;div id="folder.4.1.10"&gt;
    @others
</t>
<t tx="leo.20220622162507.151">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link68folder.4.1.10" href="en/forceSensorPropertiesDialog.htm"&gt;Force sensor property&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.152">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.11" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.11')"&gt;&lt;a name="link69folder.4.1.11" class="el" href="en/octrees.htm"&gt;OC trees&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.153">          &lt;div id="folder.4.1.11"&gt;
    @others
</t>
<t tx="leo.20220622162507.154">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link70folder.4.1.11" href="en/octreePropertiesDialog.htm"&gt;OC tree properties&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.155">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.12" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.12')"&gt;&lt;a name="link71folder.4.1.12" class="el" href="en/pointClouds.htm"&gt;Point clouds&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.156">          &lt;div id="folder.4.1.12"&gt;
    @others
</t>
<t tx="leo.20220622162507.157">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link72folder.4.1.12" href="en/pointCloudPropertiesDialog.htm"&gt;Point cloud properties&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.158">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link73folder.4.1" href="en/paths.htm"&gt;Paths&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
      &lt;/div&gt;
</t>
<t tx="leo.20220622162507.159">      &lt;p&gt;&lt;img name="imgfolder.5" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5')"&gt;&lt;a name="link74folder.5" class="el" href="en/functionality.htm"&gt;Functionality&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.16">&lt;style type="text/css"&gt;
td {
    border: none;
}
.style1 {
    margin-left: 0px;
}
.style2 {
    text-align: left;
}
&lt;/style&gt;

</t>
<t tx="leo.20220622162507.160">      &lt;div id="folder.5"&gt;
    @others
</t>
<t tx="leo.20220622162507.161">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.1')"&gt;&lt;a name="link75folder.5.1" class="el" href="en/geometricCalculations.htm"&gt;Geometric calculations&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.162">        &lt;div id="folder.5.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.163">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link76folder.5.1" href="en/collisionDetection.htm"&gt;Collision detection&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.164">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link77folder.5.1" href="en/distanceCalculation.htm"&gt;Distance calculation&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.165">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.1.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.1.1')"&gt;&lt;a name="link78folder.5.1.1" class="el" href="en/geometricPlugin.htm"&gt;Geometric plugin&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.166">          &lt;div id="folder.5.1.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.167">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link79folder.5.1.1" href="en/simGeom.htm?view=category"&gt;simGeom API reference&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.168">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.1.2" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.1.2')"&gt;&lt;a name="link80folder.5.1.2" class="el" href="en/coppeliaGeometricRoutines.htm"&gt;Coppelia geometric routines&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.169">          &lt;div id="folder.5.1.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.17">&lt;body&gt;
&lt;p&gt;This feature will search in the CoppeliaSim user manual using Google. It works only when online.&lt;/p&gt;

    @others
&lt;/body&gt;
</t>
<t tx="leo.20220622162507.170">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link81folder.5.1.2" href="en/coppeliaGeometricRoutines-api.htm?view=category"&gt;API reference&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.171">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link82folder.5.1" href="en/simIGL.htm?view=alphabetical"&gt;simIGL API reference&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.172">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.2" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.2')"&gt;&lt;a name="link83folder.5.2" class="el" href="en/kinematics.htm"&gt;Kinematics&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.173">        &lt;div id="folder.5.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.174">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link84folder.5.2" href="en/basicsOnIkGroupsAndIkElements.htm"&gt;Basics on IK groups and IK elements&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.175">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link85folder.5.2" href="en/solvingIkAndFk.htm"&gt;Solving IK and FK for any type of mechanism&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.176">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.2.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.2.1')"&gt;&lt;a name="link86folder.5.2.1" class="el" href="en/kinematicsPlugin.htm"&gt;Kinematics plugin&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.177">          &lt;div id="folder.5.2.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.178">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link87folder.5.2.1" href="en/simIK.htm?view=category"&gt;simIK API reference&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.179">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.2.2" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.5.2.2')"&gt;&lt;a name="link88folder.5.2.2" class="el" href="en/coppeliaKinematicsRoutines.htm"&gt;Coppelia kinematics routines&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.18">&lt;script&gt;
  (function() {
    var cx = '000323407853036022547:dvawi88xqo0';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
&lt;/script&gt;
&lt;gcse:search&gt;&lt;/gcse:search&gt;

</t>
<t tx="leo.20220622162507.180">          &lt;div id="folder.5.2.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.181">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link89folder.5.2.2" href="en/coppeliaKinematicsRoutines-api.htm?view=category"&gt;API reference&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.182">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.3" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.3')"&gt;&lt;a name="link90folder.5.3" class="el" href="en/dynamicsModule.htm"&gt;Dynamics&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.183">        &lt;div id="folder.5.3"&gt;
    @others
</t>
<t tx="leo.20220622162507.184">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link91folder.5.3" href="en/designingDynamicSimulations.htm"&gt;Designing dynamic simulations&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.185">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.3.1" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.5.3.1')"&gt;&lt;a name="link92folder.5.3.1" class="el" href="en/dynamicsDialog.htm"&gt;General dynamics properties&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.186">          &lt;div id="folder.5.3.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.187">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link93folder.5.3.1" href="en/dynamicsEngineDialog.htm"&gt;Dynamics engines general properties&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.188">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.4" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.4')"&gt;&lt;a name="link94folder.5.4" class="el" href="en/dataVisualizationAndOutput.htm"&gt;Data visualization/output&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.189">        &lt;div id="folder.5.4"&gt;
    @others
</t>
<t tx="leo.20220622162507.19">@path ./
&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Strict//EN"&gt;
@others
@language xml
@tabwidth -4
</t>
<t tx="leo.20220622162507.190">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link95folder.5.4" href="en/externalFrontEnd.htm"&gt;Web-browser based front-end&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.191">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link96folder.5" href="en/dataTransformation.htm"&gt;Data manipulation/transformation&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.192">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.5" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.5')"&gt;&lt;a name="link97folder.5.5" class="el" href="en/meansOfCommunication.htm"&gt;Messaging/interfaces/connectivity&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.193">        &lt;div id="folder.5.5"&gt;
    @others
</t>
<t tx="leo.20220622162507.194">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.5.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.5.1')"&gt;&lt;a name="link98folder.5.5.1" class="el" href="en/remoteApiOverview.htm"&gt;Remote API&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.195">          &lt;div id="folder.5.5.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.196">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link99folder.5.5.1" href="en/zmqRemoteApiOverview.htm"&gt;ZeroMQ remote API&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.197">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link100folder.5.5.1" href="en/wsRemoteApiOverview.htm"&gt;WebSocket remote API&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.198">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.5.2" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.5.2')"&gt;&lt;a name="link101folder.5.5.2" class="el" href="en/rosInterfaces.htm"&gt;ROS Interfaces&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.199">          &lt;div id="folder.5.5.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.2"></t>
<t tx="leo.20220622162507.20">&lt;html&gt;

    @others
</t>
<t tx="leo.20220622162507.200">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.5.2.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.5.2.1')"&gt;&lt;a name="link102folder.5.5.2.1" class="el" href="en/rosInterf.htm"&gt;ROS Interface&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.201">            &lt;div id="folder.5.5.2.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.202">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link103folder.5.5.2.1" href="en/simROS.htm?view=alphabetical"&gt;simROS API reference&lt;/a&gt;&lt;/p&gt;
            &lt;/div&gt;
</t>
<t tx="leo.20220622162507.203">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.5.2.2" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.5.5.2.2')"&gt;&lt;a name="link104folder.5.5.2.2" class="el" href="en/ros2Interface.htm"&gt;ROS 2 Interface&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.204">            &lt;div id="folder.5.5.2.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.205">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link105folder.5.5.2.2" href="en/simROS2.htm?view=alphabetical"&gt;simROS2 API reference&lt;/a&gt;&lt;/p&gt;
            &lt;/div&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.206">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link106folder.5.5" href="en/simZMQ.htm?view=alphabetical"&gt;simZMQ API reference&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.207">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link107folder.5.5" href="en/simWS.htm?view=alphabetical"&gt;simWS API reference&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.208">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link108folder.5" href="en/pathsAndTrajectories.htm"&gt;Paths/trajectories&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.209">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.6" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.6')"&gt;&lt;a name="link109folder.5.6" class="el" href="en/pathAndMotionPlanningModules.htm"&gt;Path planning&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.21">&lt;head&gt;
    @others
</t>
<t tx="leo.20220622162507.210">        &lt;div id="folder.5.6"&gt;
    @others
</t>
<t tx="leo.20220622162507.211">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link110folder.5.6" href="en/simOMPL.htm?view=alphabetical"&gt;simOMPL API reference&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.212">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.7" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.7')"&gt;&lt;a name="link111folder.5.7" class="el" href="en/syntheticVision.htm"&gt;Synthetic vision&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.213">        &lt;div id="folder.5.7"&gt;
    @others
</t>
<t tx="leo.20220622162507.214">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link112folder.5.7" href="en/simIM.htm?view=alphabetical"&gt;simIM API reference&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.215">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link113folder.5.7" href="en/simVision.htm?view=category"&gt;simVision API reference&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.216">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.8" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.8')"&gt;&lt;a name="link114folder.5.8" class="el" href="en/customUIPlugin.htm"&gt;Custom user interfaces&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.217">        &lt;div id="folder.5.8"&gt;
    @others
</t>
<t tx="leo.20220622162507.218">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link115folder.5.8" href="en/simUI.htm?view=alphabetical"&gt;simUI API reference&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.219">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link116folder.5.8" href="en/simUI-widgets.htm"&gt;simUI XML syntax&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.22">&lt;meta http-equiv="Content-Language" content="en-us"&gt;
&lt;title&gt;CoppeliaSim User Manual&lt;/title&gt;
&lt;/head&gt;

</t>
<t tx="leo.20220622162507.220">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link117folder.5.8" href="en/simQML.htm?view=alphabetical"&gt;simQML API reference&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.221">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.9" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.9')"&gt;&lt;a name="link118folder.5.9" class="el" href="en/importExport.htm"&gt;Import/export&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.222">        &lt;div id="folder.5.9"&gt;
    @others
</t>
<t tx="leo.20220622162507.223">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link119folder.5.9" href="en/xmlFormat.htm"&gt;XML format&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.224">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.9.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.9.1')"&gt;&lt;a name="link120folder.5.9.1" class="el" href="en/urdfPlugin.htm"&gt;URDF format&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.225">          &lt;div id="folder.5.9.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.226">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link121folder.5.9.1" href="en/simURDF.htm?view=alphabetical"&gt;simURDF API reference&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.227">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.9.2" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.9.2')"&gt;&lt;a name="link122folder.5.9.2" class="el" href="en/sdfPlugin.htm"&gt;SDF format&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.228">          &lt;div id="folder.5.9.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.229">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link123folder.5.9.2" href="en/simSDF.htm?view=alphabetical"&gt;simSDF API reference&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.23">&lt;frameset cols="400,*" frameborder="1" framespacing="4" bordercolor="#0B6DCE" border="4"&gt;
    @others
</t>
<t tx="leo.20220622162507.230">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link124folder.5.9" href="en/aviRecorder.htm"&gt;Video exporter&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.231">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link125folder.5.9" href="en/simAssimp.htm?view=alphabetical"&gt;simAssimp API reference&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.232">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link126folder.5.9" href="en/simGLTF.htm?view=alphabetical"&gt;simGLTF API reference&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.233">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.10" src="wb_img/plusnode.png" onclick="toggleFolder('folder.5.10')"&gt;&lt;a name="link127folder.5.10" class="el" href="en/commandLine.htm"&gt;Commands/setting&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.234">        &lt;div id="folder.5.10"&gt;
    @others
</t>
<t tx="leo.20220622162507.235">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link128folder.5.10" href="en/simLuaCmd.htm?view=alphabetical"&gt;simLuaCmd API reference&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.236">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.5.11" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.5.11')"&gt;&lt;a name="link129folder.5.11" class="el" href="en/miscellaneousFunctionality.htm"&gt;Miscellaneous&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.237">        &lt;div id="folder.5.11"&gt;
    @others
</t>
<t tx="leo.20220622162507.238">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link130folder.5.11" href="en/simSurfRec.htm?view=alphabetical"&gt;simSurfRec API reference&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.239">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link131folder.5.11" href="en/simICP.htm?view=alphabetical"&gt;simICP API reference&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.24">  &lt;frameset rows="54,*" frameborder="0" framespacing="0" bordercolor="#0B6DCE"&gt;
    @others
</t>
<t tx="leo.20220622162507.240">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link132folder.5.11" href="en/simSubprocess.htm?view=alphabetical"&gt;simSubprocess API reference&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
      &lt;/div&gt;
</t>
<t tx="leo.20220622162507.241">      &lt;p&gt;&lt;img name="imgfolder.6" src="wb_img/plusnode.png" onclick="toggleFolder('folder.6')"&gt;&lt;a name="link133folder.6" class="el" href="en/writingCode.htm"&gt;Writing code in and around CoppeliaSim&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.242">      &lt;div id="folder.6"&gt;
    @others
</t>
<t tx="leo.20220622162507.243">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.6.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.6.1')"&gt;&lt;a name="link134folder.6.1" class="el" href="en/scripts.htm"&gt;Scripts&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.244">        &lt;div id="folder.6.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.245">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.6.1.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.6.1.1')"&gt;&lt;a name="link135folder.6.1.1" class="el" href="en/embeddedScripts.htm"&gt;Embedded scripts&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.246">          &lt;div id="folder.6.1.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.247">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.6.1.1.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.6.1.1.1')"&gt;&lt;a name="link136folder.6.1.1.1" class="el" href="en/simulationScripts.htm"&gt;Simulation scripts&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.248">            &lt;div id="folder.6.1.1.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.249">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link137folder.6.1.1.1" href="en/mainScript.htm"&gt;The main script&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.25">    &lt;frame name="wb_bar" scrolling="no" src="wb_bar.html" frameborder="0" target="wb_cont"&gt;
    @others
&lt;/html&gt;
</t>
<t tx="leo.20220622162507.250">              &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link138folder.6.1.1.1" href="en/childScripts.htm"&gt;Child scripts&lt;/a&gt;&lt;/p&gt;
            &lt;/div&gt;
</t>
<t tx="leo.20220622162507.251">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link139folder.6.1.1" href="en/customizationScripts.htm"&gt;Customization scripts&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.252">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link140folder.6.1.1" href="en/scriptProperties.htm"&gt;Script dialog&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.253">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link141folder.6.1.1" href="en/scriptEditor.htm"&gt;Script editor&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.254">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link142folder.6.1" href="en/addOns.htm"&gt;Add-ons&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.255">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link143folder.6.1" href="en/sandboxScript.htm"&gt;The sandbox script&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.256">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link144folder.6.1" href="en/scriptExecution.htm"&gt;Script execution order&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.257">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link145folder.6.1" href="en/threadedAndNonThreadedCode.htm"&gt;Threaded and non-threaded script code&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.258">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.6.1.2" src="wb_img/plusnode.png" onclick="toggleFolder('folder.6.1.2')"&gt;&lt;a name="link146folder.6.1.2" class="el" href="en/callbackFunctions.htm"&gt;Callback functions&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.259">          &lt;div id="folder.6.1.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.26">    &lt;frame name="wb_tree" src="wb_tree.html" frameborder="1" target="wb_cont"&gt;
  &lt;/frameset&gt;
</t>
<t tx="leo.20220622162507.260">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link147folder.6.1.2" href="en/dynCallbackFunctions.htm"&gt;Dynamics callback functions&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.261">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link148folder.6.1.2" href="en/jointCallbackFunctions.htm"&gt;Joint callback functions&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.262">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link149folder.6.1.2" href="en/contactCallbackFunction.htm"&gt;Contact callback function&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.263">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link150folder.6.1.2" href="en/visionCallbackFunctions.htm"&gt;Vision callback functions&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.264">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link151folder.6.1.2" href="en/triggerCallbackFunctions.htm"&gt;Trigger callback functions&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.265">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link152folder.6.1.2" href="en/userConfigCallbackFunctions.htm"&gt;User config callback functions&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.266">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link153folder.6.1" href="en/luaPythonDifferences.htm"&gt;Lua vs Python scripts&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.267">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link154folder.6.1" href="en/luaCrashCourse.htm"&gt;Lua crash course&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.268">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link155folder.6" href="en/plugins.htm"&gt;Plugins&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.269">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link156folder.6" href="en/mainClientApplication.htm"&gt;The main client application&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.27">  &lt;frame name="wb_cont" src="en/welcome.htm" frameborder="0"&gt;
&lt;/frameset&gt;
</t>
<t tx="leo.20220622162507.270">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link157folder.6" href="en/accessingSceneObjects.htm"&gt;Accessing scene objects programmatically&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.271">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link158folder.6" href="en/explicitHandling.htm"&gt;Explicit and non-explicit calls&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.272">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.6.2" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.6.2')"&gt;&lt;a name="link159folder.6.2" class="el" href="en/apisOverview.htm"&gt;CoppeliaSim API framework&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.273">        &lt;div id="folder.6.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.274">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link160folder.6.2" href="en/apiFunctions.htm"&gt;Regular API reference&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.275">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link161folder.6.2" href="en/apiConstants.htm"&gt;Regular API constants&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.276">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link162folder.6.2" href="en/objectParameterIDs.htm"&gt;Object parameter IDs&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
      &lt;/div&gt;
</t>
<t tx="leo.20220622162507.277">      &lt;p&gt;&lt;img name="imgfolder.7" src="wb_img/plusnode.png" onclick="toggleFolder('folder.7')"&gt;&lt;a name="link163folder.7" class="el" href="en/simulation.htm"&gt;Simulation&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.278">      &lt;div id="folder.7"&gt;
    @others
</t>
<t tx="leo.20220622162507.279">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link164folder.7" href="en/simulationPropertiesDialog.htm"&gt;Simulation settings dialog&lt;/a&gt;&lt;/p&gt;
      &lt;/div&gt;
</t>
<t tx="leo.20220622162507.28">&lt;noframes&gt;
    @others
&lt;/noframes&gt;

</t>
<t tx="leo.20220622162507.280">      &lt;p&gt;&lt;img name="imgfolder.8" src="wb_img/plusnode.png" onclick="toggleFolder('folder.8')"&gt;&lt;a name="link165folder.8" class="el" href="en/tutorials.htm"&gt;Tutorials&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.281">      &lt;div id="folder.8"&gt;
    @others
</t>
<t tx="leo.20220622162507.282">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link166folder.8" href="en/bubbleRobTutorial.htm"&gt;BubbleRob tutorial&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.283">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link167folder.8" href="en/buildingAModelTutorial.htm"&gt;Building a clean model tutorial&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.284">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link168folder.8" href="en/lineFollowingBubbleRobTutorial.htm"&gt;Line following BubbleRob tutorial&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.285">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link169folder.8" href="en/inverseKinematicsTutorial.htm"&gt;Inverse kinematics tutorial&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.286">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link170folder.8" href="en/externalControllerTutorial.htm"&gt;External controller tutorial&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.287">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link171folder.8" href="en/pluginTutorial.htm"&gt;Plugin tutorial&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.288">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link172folder.8" href="en/robotLanguageIntegrationTutorial.htm"&gt;Robot language interpreter integration tutorial&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.289">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.8.1" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.8.1')"&gt;&lt;a name="link173folder.8.1" class="el" href="en/rosTutorial.htm"&gt;ROS tutorials&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.29">&lt;body&gt;

&lt;p&gt;This page uses frames, but your browser doesn&amp;#39;t support them.&lt;/p&gt;

&lt;/body&gt;
</t>
<t tx="leo.20220622162507.290">        &lt;div id="folder.8.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.291">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link174folder.8.1" href="en/ros1Tutorial.htm"&gt;ROS tutorial&lt;/a&gt;&lt;/p&gt;
    @others
&lt;/html&gt;
</t>
<t tx="leo.20220622162507.292">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link175folder.8.1" href="en/ros2Tutorial.htm"&gt;ROS 2 tutorial&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
      &lt;/div&gt;
</t>
<t tx="leo.20220622162507.293">      &lt;p&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link176folder" href="en/compilingCoppeliaSim.htm"&gt;Compiling CoppeliaSim&lt;/a&gt;&lt;/p&gt;
  &lt;/div&gt;
&lt;/body&gt;
</t>
<t tx="leo.20220622162507.294"></t>
<t tx="leo.20220622162507.295"></t>
<t tx="leo.20220622162507.3">@path ./
@others
@language xml
@tabwidth -4
</t>
<t tx="leo.20220622162507.30">@path ./
@others
@language xml
@tabwidth -4
</t>
<t tx="leo.20220622162507.31">&lt;html&gt;
    @others
</t>
<t tx="leo.20220622162507.32">&lt;head&gt;
&lt;title&gt;ssSearch&lt;/title&gt;
    @others
</t>
<t tx="leo.20220622162507.33">&lt;link rel="stylesheet" type="text/css" href="style.css"&gt;
&lt;/head&gt;
</t>
<t tx="leo.20220622162507.34">&lt;body&gt;
&lt;h3&gt;Simple Search&lt;/h3&gt;
    @others
</t>
<t tx="leo.20220622162507.35">&lt;blockquote&gt;
    @others
</t>
<t tx="leo.20220622162507.36">&lt;center&gt;
    @others
</t>
<t tx="leo.20220622162507.37">  &lt;applet code="ssSearch.class" width="640" height="480"&gt; 
    @others
</t>
<t tx="leo.20220622162507.38">    &lt;param name="BGCOLOR" value="0B6DCE"&gt; 
    @others
</t>
<t tx="leo.20220622162507.39">    &lt;param name="LISTAREACOLOR" value="ffffff"&gt;
    &lt;!--  Use "_self", "_blank", "_parent", "_top" or any other user-defined name --&gt;
    @others
&lt;/body&gt;&lt;/html&gt;
</t>
<t tx="leo.20220622162507.4">&lt;html&gt;
    @others
</t>
<t tx="leo.20220622162507.40">    &lt;param name="TARGETFRAME" value="_self"&gt;
    @others
&lt;/blockquote&gt;
</t>
<t tx="leo.20220622162507.41">    &lt;param name="DATAFILE" value="wb_search.txt"&gt;
    &lt;!-- The APPLETHOME param is just an acknowledgement --&gt;
    &lt;!-- Do not edit the value of APPLETHOME param --&gt;
    @others
&lt;/center&gt;
</t>
<t tx="leo.20220622162507.42">    &lt;param name="APPLETHOME" value="http://www.geocities.com/SiliconValley/Lakes/5365/index.html"&gt;
  &lt;/applet&gt;
</t>
<t tx="leo.20220622162507.43">@path ./
&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Strict//EN"&gt;
@others
@language xml
@tabwidth -4
</t>
<t tx="leo.20220622162507.44">&lt;html&gt;
    @others
</t>
<t tx="leo.20220622162507.45">&lt;head&gt;
    @others
</t>
<t tx="leo.20220622162507.46">  &lt;meta http-equiv="Content-Language" content="en-us" &gt;
  &lt;title&gt;Bar&lt;/title&gt;
    @others
</t>
<t tx="leo.20220622162507.47">  &lt;base target="wb_cont"&gt;
    @others
&lt;/head&gt;

</t>
<t tx="leo.20220622162507.48">  &lt;style type="text/css"&gt;
  .navigation{
    padding: 0;
    margin: 0;
    white-space: nowrap;
    border: 1px solid #7F93C7;
    background-color: #FFFFFF;
    line-height: 19px;
  }
  .navigation p { margin: 1px; white-space: nowrap; }
  .navigation img { vertical-align: middle; }
  &lt;/style&gt;
</t>
<t tx="leo.20220622162507.49">&lt;body style="margin: 2px; background-color: #F1F1F1"&gt; 
    @others
</t>
<t tx="leo.20220622162507.5">&lt;head&gt;
    @others
</t>
<t tx="leo.20220622162507.50">  &lt;div class="navigation"&gt;
    @others
</t>
<t tx="leo.20220622162507.51">    &lt;p&gt;&lt;img alt="Expand All Nodes" src="wb_img/showall.png" onclick="parent.wb_tree.showAllFolders()" onmouseover="this.src='wb_img/showall_over.png'" onmouseout="this.src='wb_img/showall.png'"&gt;&lt;img alt="Contract All Nodes" src="wb_img/hideall.png" onclick="parent.wb_tree.hideAllFolders()" onmouseover="this.src='wb_img/hideall_over.png'" onmouseout="this.src='wb_img/hideall.png'"&gt;&lt;img alt="Sync Tree with Contents" src="wb_img/sync.png" onclick="parent.wb_tree.syncContents()" onmouseover="this.src='wb_img/sync_over.png'" onmouseout="this.src='wb_img/sync.png'"&gt;&lt;img alt="Next Link" src="wb_img/next.png" onclick="parent.wb_tree.nextContents()" onmouseover="this.src='wb_img/next_over.png'" onmouseout="this.src='wb_img/next.png'"&gt;&lt;img alt="Previous Link" src="wb_img/previous.png" onclick="parent.wb_tree.prevContents()" onmouseover="this.src='wb_img/previous_over.png'" onmouseout="this.src='wb_img/previous.png'"&gt;&lt;/p&gt;
    &lt;p&gt;User manual search (&lt;a class="contact" href="ssSearch.html"&gt;offline&lt;/a&gt;, &lt;a class="contact" href="gSearch.html"&gt;online&lt;/a&gt;), &lt;a class="contact" href="gfSearch.html"&gt;forum search&lt;/a&gt;&lt;/p&gt;
  &lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;
</t>
<t tx="leo.20220622162507.52">@path ./
&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Strict//EN"&gt;
@others
@language xml
@tabwidth -4
</t>
<t tx="leo.20220622162507.53">&lt;html&gt;
    @others
</t>
<t tx="leo.20220622162507.54">&lt;head&gt;
    @others
</t>
<t tx="leo.20220622162507.55">  &lt;meta http-equiv="Content-Language" content="en-us" &gt;
  &lt;title&gt;Tree&lt;/title&gt;
    @others
</t>
<t tx="leo.20220622162507.56">  &lt;base target="wb_cont"&gt;
    @others
&lt;/head&gt;

</t>
<t tx="leo.20220622162507.57">  &lt;style type="text/css"&gt;
  .tree { font-family: helvetica, sans-serif; font-size: 10pt; }
  .tree h3 {
    margin: 5px 0px 0px 0px;
    font-size: 12pt;
  }
  .tree p { margin: 0px; white-space: nowrap; }
  .tree p.sep { margin: 0px; white-space: nowrap; line-height: 8px; font-size: 5px; }
  .tree div { display: none; margin: 0px; }
  .tree img { vertical-align: middle; }
  .tree a.el { text-decoration: none; margin-left: 4px; color: #003366; }
  .tree a:hover { text-decoration: none; background-color: #e0e0ff }
  &lt;/style&gt;
</t>
<t tx="leo.20220622162507.58">  &lt;script type="text/javascript"&gt;
  lastLink = null;

  function hideFolder(folder, id) 
  {
    var imageNode = document.images["img" + id];
    if (imageNode != null) 
    {
      var len = imageNode.src.length;
      if (imageNode.src.substring(len-8,len-4) == "last")
        imageNode.src = "wb_img/plusnodelast.png";
      else if (imageNode.src.substring(len-8,len-4) == "node")
        imageNode.src = "wb_img/plusnode.png";
    }                          
    folder.style.display = "none";
  }

  function showFolder(folder, id) 
  {
    var imageNode = document.images["img" + id];
    if (imageNode != null) 
    {
      var len = imageNode.src.length;
      if (imageNode.src.substring(len-8,len-4) == "last")
        imageNode.src = "wb_img/minusnodelast.png";
      else if (imageNode.src.substring(len-8,len-4) == "node")
        imageNode.src = "wb_img/minusnode.png";
    }
    folder.style.display = "block";
  }    

  function toggleFolder(id) 
  {
    var folder = document.getElementById(id);
    if (folder.style.display == "block") 
      hideFolder(folder, id);
    else 
      showFolder(folder, id);
  }

  function setFoldersAtLevel(level, show) 
  {                                    
    var i = 1;
    do
    {
      var folder_id = level + "." + i;
      var id = "folder" + folder_id;
      var folder = document.getElementById(id);
      if (folder != null)
      {
        setFoldersAtLevel(folder_id, show);

        if (show)
          showFolder(folder, id);
        else
          hideFolder(folder, id);
      }
      i++;
    } while(folder != null);
  }

  function showAllFolders() 
  {                                    
    setFoldersAtLevel("", true); 
  }

  function hideAllFolders() 
  {                                    
    setFoldersAtLevel("", false); 
  }

  function getFolderId(name)
  {  
    return name.substring(name.indexOf("folder"), name.length);
  }

  function showFolderRec(id)
  {
    var folder = document.getElementById(id);
    if (folder != null)
    {
      showFolder(folder, id);

      var parent_id = id.substring(0, id.lastIndexOf("."))
      if (parent_id != null &amp;&amp; parent_id != "folder")
      {
         showFolderRec(parent_id)
      }
    }
  }           

  function clearLastLink()
  {
    if (lastLink != null)
    {
      lastLink.style.color = ""  
      lastLink = null;
    }
  }                 

  function goToLink(link)
  {                  
    var id = getFolderId(link.name);
    showFolderRec(id);
    location.hash = "#" + link.name;
    link.style.color = "#ff0000";  

    clearLastLink();
    lastLink = link;
  }

  function syncContents()
  {
    var cur_topic = parent.wb_cont.location.href 

    for (var i = 0; i &lt; document.links.length; i++) 
    {      
      var link = document.links[i];
      if (cur_topic == link.href)
      {                  
        goToLink(link)
        return
      }
    }                                 
  }

  function nextContents()
  {
    var cur_topic = parent.wb_cont.location.href 

    for (var i = 0; i &lt; document.links.length; i++) 
    {      
      var link = document.links[i];
      if (cur_topic == link.href)
      {        
        if (i == document.links.length-1)
          link = document.links[0];
        else
          link = document.links[i+1];  

        goToLink(link)
        parent.wb_cont.location.href = link.href;
        return
      }
    }                                 
  }

  function prevContents()
  {
    var cur_topic = parent.wb_cont.location.href 
    var prev_link = document.links[document.links.length-1]

    for (var i = 0; i &lt; document.links.length; i++) 
    {      
      var link = document.links[i];
      if (cur_topic == link.href)
      {        
        if (i == 0)
          link = document.links[document.links.length-1];
        else
          link = document.links[i-1];

        goToLink(link)
        parent.wb_cont.location.href = link.href;
        return
      }
    }                                 
  }

  function showStartPage()
  {
    var full_url = parent.document.URL;
    if (full_url == null)
      return; 

    var param = full_url.substring(full_url.indexOf("?") + 1, full_url.length);
    if (param == null)
      return;

    var param_url = param.substring(param.indexOf("url=") + 4, param.length);
    if (param_url == null)
      return;

    var param_len = param_url.length;                                    
    for (var i = 0; i &lt; document.links.length; i++) 
    {      
      var link = document.links[i];
      var link_url = link.href.substring(link.href.length-param_len, link.href.length)
      if (link_url == param_url)
      {
        goToLink(link)
        parent.wb_cont.location.href = link.href;
        return
      }
    }                                 
  }
  &lt;/script&gt;
</t>
<t tx="leo.20220622162507.59">&lt;body style="margin: 2px; background-color: #F1F1F1" onload="showStartPage()"&gt; 
    @others
</t>
<t tx="leo.20220622162507.6">&lt;meta http-equiv="Content-Language" content="en-us"&gt;
&lt;title&gt;gSearch&lt;/title&gt;
    @others
&lt;/html&gt;
</t>
<t tx="leo.20220622162507.60">  &lt;div class="tree" onmouseout="clearLastLink()"&gt;
    &lt;h3&gt;&lt;a name="link0folder.0" class="el" href="en/welcome.htm"&gt;CoppeliaSim User Manual&lt;/a&gt;&lt;/h3&gt;
    @others
</t>
<t tx="leo.20220622162507.61">      &lt;p&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link1folder" href="en/coppeliaSimFeatures.htm"&gt;Main features&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.62">      &lt;p&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link2folder" href="en/versionInfo.htm"&gt;Version history&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.63">      &lt;p&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link3folder" href="en/licensing.htm"&gt;Licensing&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.64">      &lt;p&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link4folder" href="en/acknowledgments.htm"&gt;Acknowledgments and credits&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.65">      &lt;p&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link5folder" href="en/overviewTranslations.htm"&gt;Overview in other languages&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.66">      &lt;p&gt;&lt;img name="imgfolder.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.1')"&gt;&lt;a name="link6folder.1" class="el" href="en/userInterface.htm"&gt;User interface&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.67">      &lt;div id="folder.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.68">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link7folder.1" href="en/pagesAndViews.htm"&gt;Pages and views&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.69">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.1.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.1.1')"&gt;&lt;a name="link8folder.1.1" class="el" href="en/coordinateDialog.htm"&gt;Position/orientation manipulation&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.7">&lt;link rel="stylesheet" type="text/css" href="style.css"&gt;

    @others
&lt;/head&gt;
</t>
<t tx="leo.20220622162507.70">        &lt;div id="folder.1.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.71">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link9folder.1.1" href="en/positionDialog.htm"&gt;Position dialog&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.72">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link10folder.1.1" href="en/orientationDialog.htm"&gt;Orientation dialog&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.73">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link11folder.1.1" href="en/objectMovement.htm"&gt;Object movement via the mouse&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20220622162507.74">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link12folder.1" href="en/positionOrientationTransformation.htm"&gt;On positions, orientations and transformations&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.75">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link13folder.1" href="en/settings.htm"&gt;User settings&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.76">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link14folder.1" href="en/shortcuts.htm"&gt;Shortcuts&lt;/a&gt;&lt;/p&gt;
      &lt;/div&gt;
</t>
<t tx="leo.20220622162507.77">      &lt;p&gt;&lt;img name="imgfolder.2" src="wb_img/plusnode.png" onclick="toggleFolder('folder.2')"&gt;&lt;a name="link15folder.2" class="el" href="en/scenesAndModels.htm"&gt;Scenes and models&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.78">      &lt;div id="folder.2"&gt;
    @others
</t>
<t tx="leo.20220622162507.79">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link16folder.2" href="en/scenes.htm"&gt;Scenes&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.8">&lt;style type="text/css"&gt;
td {
    border: none;
}
.style1 {
    margin-left: 0px;
}
.style2 {
    text-align: left;
}
&lt;/style&gt;

</t>
<t tx="leo.20220622162507.80">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.2.1" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.2.1')"&gt;&lt;a name="link17folder.2.1" class="el" href="en/models.htm"&gt;Models&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.81">        &lt;div id="folder.2.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.82">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link18folder.2.1" href="en/modelDialog.htm"&gt;Model dialog&lt;/a&gt;&lt;/p&gt;
        &lt;/div&gt;
      &lt;/div&gt;
</t>
<t tx="leo.20220622162507.83">      &lt;p&gt;&lt;img name="imgfolder.3" src="wb_img/plusnode.png" onclick="toggleFolder('folder.3')"&gt;&lt;a name="link19folder.3" class="el" href="en/environment.htm"&gt;Environment&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.84">      &lt;div id="folder.3"&gt;
    @others
</t>
<t tx="leo.20220622162507.85">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link20folder.3" href="en/environmentPropertiesDialog.htm"&gt;Environment dialog&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.86">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link21folder.3" href="en/textureDialog.htm"&gt;Texture dialog&lt;/a&gt;&lt;/p&gt;
      &lt;/div&gt;
</t>
<t tx="leo.20220622162507.87">      &lt;p&gt;&lt;img name="imgfolder.4" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4')"&gt;&lt;a name="link22folder.4" class="el" href="en/entities.htm"&gt;Entities&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.88">      &lt;div id="folder.4"&gt;
    @others
</t>
<t tx="leo.20220622162507.89">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link23folder.4" href="en/collections.htm"&gt;Collections&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.9">&lt;body&gt;
&lt;p&gt;This feature will search in the CoppeliaSim/V-REP forum using Google. It works only when online.&lt;/p&gt;

    @others
&lt;/body&gt;
</t>
<t tx="leo.20220622162507.90">        &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img name="imgfolder.4.1" src="wb_img/plusnodelast.png" onclick="toggleFolder('folder.4.1')"&gt;&lt;a name="link24folder.4.1" class="el" href="en/objects.htm"&gt;Scene objects&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.91">        &lt;div id="folder.4.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.92">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img name="imgfolder.4.1.1" src="wb_img/plusnode.png" onclick="toggleFolder('folder.4.1.1')"&gt;&lt;a name="link25folder.4.1.1" class="el" href="en/sceneObjectPropertiesDialog.htm"&gt;Object properties&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.93">          &lt;div id="folder.4.1.1"&gt;
    @others
</t>
<t tx="leo.20220622162507.94">            &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/nodelast.png"&gt;&lt;a class="el" name="link26folder.4.1.1" href="en/commonPropertiesDialog.htm"&gt;Object common properties&lt;/a&gt;&lt;/p&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20220622162507.95">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link27folder.4.1" href="en/collidableObjects.htm"&gt;Collidable objects&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.96">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link28folder.4.1" href="en/measurableObjects.htm"&gt;Measurable objects&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.97">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link29folder.4.1" href="en/detectableObjects.htm"&gt;Detectable objects&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.98">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link30folder.4.1" href="en/viewableObjects.htm"&gt;Viewable objects&lt;/a&gt;&lt;/p&gt;
    @others
</t>
<t tx="leo.20220622162507.99">          &lt;p&gt;&lt;img src="wb_img/vertline.png"&gt;&lt;img src="wb_img/blank.png"&gt;&lt;img src="wb_img/node.png"&gt;&lt;a class="el" name="link31folder.4.1" href="en/convexHull.htm"&gt;Convex hull&lt;/a&gt;&lt;/p&gt;
    @others
</t>
</tnodes>
</leo_file>
